config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    validates :content, length: { maximum: 140 }
    belongs_to :user 
    validates :content, presence: true  
  end
  

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts, dependent: :destroy
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "hello, world!"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :set_micropost, only: %i[show edit update destroy]
  
    def index
      @microposts = Micropost.all
    end
  
    def show
    end
  
    def new
      @micropost = Micropost.new
    end
  
    def create
      @micropost = Micropost.new(micropost_params)
  
      if @micropost.save
        redirect_to @micropost, notice: 'Micropost was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @micropost.update(micropost_params)
        redirect_to @micropost, notice: 'Micropost was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @micropost.destroy
      redirect_to microposts_url, notice: 'Micropost was successfully destroyed.'
    end
  
    private
  
      def set_micropost
        @micropost = Micropost.find(params[:id])
      end
  
      def micropost_params
        params.require(:micropost).permit(:content, :user_id)
      end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]
  
    def index
      @users = User.all
    end
  
    def show
        @micropost = @user.microposts.first
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to @user, notice: 'User was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end
  
    private
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:name, :email)
    end
 end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
    <% if micropost.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>
  
        <ul>
          <% micropost.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
  
    <div class="field">
      <%= form.label :user_id %>
      <%= form.number_field :user_id %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/microposts/edit.html.erb
<h1>Edit Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Microposts</h1>

<%= link_to 'New Micropost', new_micropost_path %>

<ul>
  <% @microposts.each do |micropost| %>
    <li>
      <%= micropost.content %> - <%= micropost.user_id %>
      <%= link_to 'Show', micropost_path(micropost) %> |
      <%= link_to 'Edit', edit_micropost_path(micropost) %> |
      <%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<h1>Micropost</h1>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<p>
  <strong>User ID:</strong>
  <%= @micropost.content %>
</p>